version: '3.9'

services:
  grafana:
    image: grafana/grafana:8.3.1
    hostname: grafana
    ports:
      - "3000:3000"
    environment:
      GF_INSTALL_PLUGINS: "marcusolsson-json-datasource 1.3.0,michaeldmoore-multistat-panel 1.7.2,michaeldmoore-scatter-panel 1.0.0,natel-plotly-panel 0.0.7,marcusolsson-dynamictext-panel 1.8.0,marcusolsson-static-datasource 1.4.3"
      GF_SECURITY_ADMIN_USER: ${GRAFANA_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD}
      GF_LOG_LEVEL: info
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: fondus-jsontext-panel
    volumes:
      - ./provisioning/datasources/config.yml:/etc/grafana/provisioning/datasources/default.yml
      - ../dist:/var/lib/grafana/plugins/fondus-jsontext-panel
    networks:
      - grafana

networks:
  grafana:
    name: grafana
    driver: bridge
  auth:
    external: true
