version: '3.9'

services:
  grafana:
    image: grafana/grafana:8.4.1
    hostname: grafana
    ports:
      - "3000:3000"
    environment:
      GF_INSTALL_PLUGINS: "marcusolsson-json-datasource 1.3.0,marcusolsson-dynamictext-panel 1.8.0"
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: fondus-jsonpretty-panel
    volumes:
      - ./provisioning/datasources/config.yml:/etc/grafana/provisioning/datasources/default.yml
      - ../dist:/var/lib/grafana/plugins/fondus-jsonpretty-panel
    networks:
      - grafana

networks:
  grafana:
    name: grafana
    driver: bridge
